# Generated by Django 4.0.5 on 2022-06-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_post_host_answer_post_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
